### ISSUE TITLE
velodyne_reduced

### ISSUE THREAD

**Issue by Orbis36** [Nightmare-n/PVT-SSD#3]
Hi there
Thanks for your work first.
My question is for velodyne_reduced, how can I generate it? (64 lines in kitti_dataset.py)
Or it's the same thing as Velodyne?

**Comment by Nightmare-n** [comment]
You could directly change to velodyne by setting FOV_POINTS_ONLY=True. (velodyne_reduced means the preprocessed point clouds in the fov).
